# Generated by Django 4.0.1 on 2022-08-23 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swagApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='zara',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=20)),
                ('phone', models.IntegerField()),
            ],
        ),
    ]
